version: "3.0"
services:
  spherical-env:
    image: qiangzibro/spherical_image_segmentation:latest
    build:
        context: ./
        dockerfile: Dockerfile
    volumes:
        - .:/workspace
    tty: true
    network_mode: "host"
    environment:
      - "http_proxy=${http_proxy}"
      - "https_proxy=${https_proxy}"
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]

  jupyterlab:
    image: qiangzibro/spherical_image_segmentation:latest
    build:
        context: ./
        dockerfile: Dockerfile

    network_mode: host
    environment:
      - "http_proxy=${http_proxy}"
      - "https_proxy=${https_proxy}"

    volumes:
        - .:/workspace
    entrypoint: sh -c "jupyter lab --ip=0.0.0.0 --port=11000 --no-browser --notebook-dir=/workspace --allow-root --NotebookApp.token='spherical' --NotebookApp.password='spherical'"
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
